# Generated by Django 3.0.6 on 2020-05-11 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('visibility', models.BooleanField(default=True, verbose_name='Публичная игра')),
                ('is_reported', models.BooleanField(default=False, verbose_name='Создан отчет')),
                ('capacity', models.SmallIntegerField(blank=True, default=0, verbose_name='Вместимость')),
                ('cost', models.SmallIntegerField(blank=True, default=0, verbose_name='Цена')),
                ('datetime', models.DateTimeField(verbose_name='Начало')),
                ('duration', models.DurationField(blank=True, help_text='В минутах', null=True, verbose_name='Длительность')),
                ('responsible', models.ForeignKey(limit_choices_to={'groups__name': 'Создатели игр'}, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_user', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'игра',
                'verbose_name_plural': 'игры',
            },
        ),
    ]
