# Generated by Django 3.0.6 on 2020-05-11 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20200511_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='title',
        ),
    ]
