# Generated by Django 3.0.6 on 2020-05-11 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
        ('games', '0003_remove_game_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='court',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courts.Court'),
            preserve_default=False,
        ),
    ]
