# Generated by Django 3.0.6 on 2020-05-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
        ('users', '0002_auto_20200517_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sport_roles',
            field=models.ManyToManyField(blank=True, to='sports.SportRole'),
        ),
    ]
