# Generated by Django 3.0.6 on 2020-05-11 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amplua',
            new_name='SportRole',
        ),
    ]
