# Generated by Django 3.0.6 on 2020-05-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_auto_20200517_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
