# Generated by Django 3.0.6 on 2020-05-17 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0003_court_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courts.Place', verbose_name='Место'),
            preserve_default=False,
        ),
    ]
