# Generated by Django 3.0.6 on 2020-05-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0004_court_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(help_text='В формате "Московская 9б', max_length=500, unique=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Заполняется автоматически', null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Заполняется автоматически', null=True, verbose_name='Долгота'),
        ),
    ]
