# Generated by Django 3.0.6 on 2020-05-13 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.SmallIntegerField(blank=True, default=0, verbose_name='Вместимость')),
                ('cost', models.SmallIntegerField(blank=True, default=0, verbose_name='Цена')),
                ('datetime', models.DateTimeField(verbose_name='Начало')),
                ('duration', models.DurationField(blank=True, help_text='ЧЧ:ММ:СС', null=True, verbose_name='Длительность')),
                ('visibility', models.BooleanField(default=True, verbose_name='Публичная игра')),
                ('is_reported', models.BooleanField(default=False, verbose_name='Создан отчет')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courts.Court')),
            ],
            options={
                'verbose_name': 'игра',
                'verbose_name_plural': 'игры',
            },
        ),
    ]
