# Generated by Django 3.0.6 on 2020-05-17 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0002_auto_20200513_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGameRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Дата действия')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Записался'), (3, 'Отписался'), (2, 'В резерве'), (4, 'Посетил'), (5, 'Не пришел')], null=True, verbose_name='Действие')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game', verbose_name='Игра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usergame', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'запись на игру',
                'verbose_name_plural': 'записи на игру',
            },
        ),
    ]
