# Generated by Django 3.0.6 on 2020-05-17 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_usergamerelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergamerelation',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='games.Game', verbose_name='Игра'),
        ),
    ]
