# Generated by Django 3.0.6 on 2020-05-13 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название вида спорта')),
            ],
            options={
                'verbose_name': 'Вид спорта',
                'verbose_name_plural': 'Виды спорта',
            },
        ),
        migrations.CreateModel(
            name='SportRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('sport_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.SportType', verbose_name='Вид спорта')),
            ],
            options={
                'verbose_name': 'амплуа',
                'verbose_name_plural': 'амплуа',
            },
        ),
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название типа игры')),
                ('description', models.TextField(blank=True, verbose_name='Описание формата')),
                ('sport_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.SportType', verbose_name='Вид спорта')),
            ],
            options={
                'verbose_name': 'Тип игры',
                'verbose_name_plural': 'Типы игры',
            },
        ),
    ]
